# Generated by Django 3.1.6 on 2021-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='productimg'),
        ),
    ]
