# Generated by Django 3.1.6 on 2021-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210521_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_child1',
            field=models.ImageField(blank=True, default='productchild1.png', null=True, upload_to='productimg_child'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_child2',
            field=models.ImageField(blank=True, default='productchild2.png', null=True, upload_to='productimg_child'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_child3',
            field=models.ImageField(blank=True, default='productchild3.png', null=True, upload_to='productimg_child'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product.png', upload_to='productimg'),
        ),
    ]
