# Generated by Django 3.1.6 on 2021-05-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210524_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_child1_min',
            field=models.ImageField(blank=True, default='productchild1_min.png', null=True, upload_to='productimg_child_min'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_child2_min',
            field=models.ImageField(blank=True, default='productchild2_min.png', null=True, upload_to='productimg_child_min'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_child3_min',
            field=models.ImageField(blank=True, default='productchild3_min.png', null=True, upload_to='productimg_child_min'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_min',
            field=models.ImageField(default='product_min.png', upload_to='productimg_min'),
        ),
    ]
