# Generated by Django 3.1.6 on 2021-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210529_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
